---
title: "Quadvariate Viz"
execute:
  echo: true
  warning: false
  error: false

format: 
  html: 
    code-fold: true

---

Use this file to generate a professional looking **quadvariate** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.
```{r}
library(tidyverse)
library (sf)
library (maps)
library (RColorBrewer)
library (gplots)
library(socviz)
library (leaflet)
library (devtools)
library(ggthemes)
library(viridis)
```

```{r}
weather <- read.csv("https://mac-stat.github.io/data/weather_3_locations.csv") |> 
  mutate(date = as.Date(date))  
```


```{r}
#| fig-cap: "Temperature readings at 3:00 AM and 9:00 AM across multiple locations, with indications of whether rainfall occurred. The graph highlights temperature variations and potential correlations with rainfall."

#| fig-alt: "A scatter plot displaying temperature readings at 3:00 AM and 9:00 AM for multiple locations, with additional data indicating whether it rained. The x-axis temperature at 9:00 AM, while the y-axis shows temperature values at 3:00 PM. Different shapes distinguish rainy and non-rainy conditions, illustrating potential trends in temperature shifts due to precipitation. The biggest takeaways are that the there is a medium/strong and positive relationship in all of the locations, and that Uluru has typically the greatest temperatures. Additionally, there seems to be more rain in hobart than the other two locations. The data is from weather-https://mac-stat.github.io/data/weather_3_locations.csv"

ggplot(weather, aes(y = temp3pm, x = temp9am, color = location, shape = raintoday)) + 
  geom_point(alpha=0.5)+
labs(y="Temperature at 3:00 PM", x="Temperature at 9:00 AM", color="Location", shape="Rain", title="Temperature Variations and Rainfall by Location at 3:00 AM and 9:00 AM", caption="")+
  scale_color_viridis_d()
```

