---
title: "Spatial Viz"
---

Use this file to generate a professional looking **spatial** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.
```{r}
library (sf)
library (maps)
library (RColorBrewer)
library (gplots)
library(socviz)
library (leaflet)
library (devtools)
library(ggthemes)
```


```{r}
starbucks <- read.csv("https://mac-stat.github.io/data/starbucks.csv")
```

```{r}
library(dplyr)

# Check and rename if necessary
starbucks <- starbucks %>%
  rename_all(tolower)  # Converts all column names to lowercase

# Use the correct column name
starbucks %>%
  filter(country == "US", state.province == "MN")  # Adjust based on actual column name

```

```{r}
starbucks_mn <- starbucks |>   
  filter(state.province== "MN")
```


```{r}
#|fig_cap: "A spatial point map displaying the locations of Starbucks stores within Minnesota. The distribution highlights store density in the Twin Cities which is the major metropolitan area."

#|fig_alt: "A point map (interactive) of Minnesota showing the locations of Starbucks stores. Densely clustered points appear in major cities, with sparser distribution in rural areas. Another key takeaway is that there are more concentrated in the Twin Cities than the rest of Minnesota. The map provides a visual representation of Starbucks' geographic presence across the state. Data is from starbucks https://mac-stat.github.io/data/starbucks.csv".

leaflet(data = starbucks_mn) |> 
  addTiles() |> 
  addCircles(color = col2hex("darkgreen"))
```



