---
title: "Trivariate Viz"
execute:
  echo: true
  warning: false
  error: false

format: 
  html: 
    code-fold: true
---


```{r}
library(tidyverse)
library (sf)
library (maps)
library (RColorBrewer)
library (gplots)
library(socviz)
library (leaflet)
library (devtools)
library(ggthemes)
library(viridis)
```

```{r}
weather <- read.csv("https://mac-stat.github.io/data/weather_3_locations.csv") |> 
  mutate(date = as.Date(date))  
```


```{r}
#|fig-cap: "This figure shows the relationship between the temperature at 9:00 AM and 3:00 PM in the 3 locations; Hobart, Uluru, and Wollogong. The x-axis shows the temperature at 3:00 pm, y-axis shows the temperature at 9:00 am, and the colors differentiate the location." 

#|fig_alt: " This visualization is a scatter plot with 3 different colors that represent each location and their correlating temperatures. The biggest takeaways are that the there is a medium/strong and positive relationship in all of the locations, and that Uluru has typically the greatest temperatures. The data is from weather-https://mac-stat.github.io/data/weather_3_locations.csv"

ggplot(weather, aes(y = temp3pm, x = temp9am, color = location)) + 
  geom_point(alpha=0.5)+
  labs(x="Temperature at 3:00 PM", y="Temperature at 9:00 AM", color="Location",title="Comparing Temperatures of Different Times of the Day in Locations", caption= "Data from: TidyTuesday Github Repository, Created by: Martha Miller, Date: 02/23/2025")+
  scale_color_viridis_d()
```



